// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intravision/labour/task.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId     string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Assigner   string `protobuf:"bytes,3,opt,name=assigner,proto3" json:"assigner,omitempty"`
	State      int32  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	BeginTask  uint64 `protobuf:"varint,5,opt,name=beginTask,proto3" json:"beginTask,omitempty"`
	Deadline   uint64 `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	FinishTask uint64 `protobuf:"varint,7,opt,name=finishTask,proto3" json:"finishTask,omitempty"`
	Wager      string `protobuf:"bytes,8,opt,name=wager,proto3" json:"wager,omitempty"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_64fb2ef5a939280c, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Task.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return m.Size()
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Task) GetAssigner() string {
	if m != nil {
		return m.Assigner
	}
	return ""
}

func (m *Task) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Task) GetBeginTask() uint64 {
	if m != nil {
		return m.BeginTask
	}
	return 0
}

func (m *Task) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *Task) GetFinishTask() uint64 {
	if m != nil {
		return m.FinishTask
	}
	return 0
}

func (m *Task) GetWager() string {
	if m != nil {
		return m.Wager
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "intravision.labour.Task")
}

func init() { proto.RegisterFile("intravision/labour/task.proto", fileDescriptor_64fb2ef5a939280c) }

var fileDescriptor_64fb2ef5a939280c = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x4e, 0x85, 0x30,
	0x18, 0xc5, 0x29, 0x02, 0xde, 0xdb, 0xc1, 0xa1, 0x31, 0xa6, 0x31, 0xda, 0x10, 0x27, 0x26, 0x18,
	0x7c, 0x03, 0x27, 0x5d, 0x89, 0x93, 0x5b, 0xb1, 0xb5, 0xf7, 0xcb, 0xe5, 0xb6, 0x37, 0x6d, 0xf1,
	0xcf, 0x5b, 0xf8, 0x58, 0x8e, 0x8c, 0x8e, 0x06, 0x5e, 0xc4, 0x50, 0x0c, 0x32, 0xfe, 0xbe, 0x5f,
	0x4e, 0x4f, 0x73, 0xf0, 0x35, 0x68, 0x6f, 0xf9, 0x2b, 0x38, 0x30, 0xba, 0x6a, 0x79, 0x63, 0x3a,
	0x5b, 0x79, 0xee, 0xf6, 0xe5, 0xd1, 0x1a, 0x6f, 0x08, 0x59, 0xe9, 0x72, 0xd6, 0x37, 0x3d, 0xc2,
	0xc9, 0x23, 0x77, 0x7b, 0x72, 0x86, 0x63, 0x10, 0x14, 0xe5, 0xa8, 0x48, 0xea, 0x18, 0x04, 0xb9,
	0xc0, 0xd9, 0x14, 0x7d, 0x10, 0x34, 0xce, 0x51, 0xb1, 0xad, 0xff, 0x88, 0x5c, 0xe2, 0x0d, 0x77,
	0x0e, 0x94, 0x96, 0x96, 0x9e, 0x04, 0xb3, 0x30, 0x39, 0xc7, 0xa9, 0xf3, 0xdc, 0x4b, 0x9a, 0xe4,
	0xa8, 0x48, 0xeb, 0x19, 0xc8, 0x15, 0xde, 0x36, 0x52, 0x81, 0x9e, 0x6a, 0x68, 0x1a, 0x0a, 0xfe,
	0x0f, 0xd3, 0x7b, 0x42, 0x72, 0xd1, 0x82, 0x96, 0x34, 0x0b, 0x72, 0x61, 0xc2, 0x30, 0x7e, 0x01,
	0x0d, 0x6e, 0x17, 0xa2, 0xa7, 0xc1, 0xae, 0x2e, 0x53, 0xdf, 0x1b, 0x57, 0xd2, 0xd2, 0x4d, 0xf8,
	0xc8, 0x0c, 0x77, 0xf7, 0x5f, 0x03, 0x43, 0xfd, 0xc0, 0xd0, 0xcf, 0xc0, 0xd0, 0xe7, 0xc8, 0xa2,
	0x7e, 0x64, 0xd1, 0xf7, 0xc8, 0xa2, 0xa7, 0x52, 0x81, 0xdf, 0x75, 0x4d, 0xf9, 0x6c, 0x0e, 0xd5,
	0x41, 0xda, 0x16, 0xb4, 0x32, 0xd5, 0x7a, 0xb3, 0xf7, 0x65, 0xb5, 0x8f, 0xa3, 0x74, 0x4d, 0x16,
	0x76, 0xbb, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x21, 0xf6, 0xa0, 0xb6, 0x58, 0x01, 0x00, 0x00,
}

func (m *Task) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Wager) > 0 {
		i -= len(m.Wager)
		copy(dAtA[i:], m.Wager)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Wager)))
		i--
		dAtA[i] = 0x42
	}
	if m.FinishTask != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.FinishTask))
		i--
		dAtA[i] = 0x38
	}
	if m.Deadline != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x30
	}
	if m.BeginTask != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.BeginTask))
		i--
		dAtA[i] = 0x28
	}
	if m.State != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Assigner) > 0 {
		i -= len(m.Assigner)
		copy(dAtA[i:], m.Assigner)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Assigner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTask(dAtA []byte, offset int, v uint64) int {
	offset -= sovTask(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTask(uint64(m.Id))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Assigner)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovTask(uint64(m.State))
	}
	if m.BeginTask != 0 {
		n += 1 + sovTask(uint64(m.BeginTask))
	}
	if m.Deadline != 0 {
		n += 1 + sovTask(uint64(m.Deadline))
	}
	if m.FinishTask != 0 {
		n += 1 + sovTask(uint64(m.FinishTask))
	}
	l = len(m.Wager)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	return n
}

func sovTask(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTask(x uint64) (n int) {
	return sovTask(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Task) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Task: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Task: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assigner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assigner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeginTask", wireType)
			}
			m.BeginTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeginTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinishTask", wireType)
			}
			m.FinishTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinishTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTask(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTask
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTask
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTask
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTask
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTask        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTask          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTask = fmt.Errorf("proto: unexpected end of group")
)
