// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intravision/labour/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgWork struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Worker      string `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	Taskid      string `protobuf:"bytes,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	BeginWork   uint64 `protobuf:"varint,4,opt,name=beginWork,proto3" json:"beginWork,omitempty"`
	FinishWork  uint64 `protobuf:"varint,5,opt,name=finishWork,proto3" json:"finishWork,omitempty"`
	WorkingTime int32  `protobuf:"varint,6,opt,name=workingTime,proto3" json:"workingTime,omitempty"`
}

func (m *MsgWork) Reset()         { *m = MsgWork{} }
func (m *MsgWork) String() string { return proto.CompactTextString(m) }
func (*MsgWork) ProtoMessage()    {}
func (*MsgWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{2}
}
func (m *MsgWork) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWork.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWork.Merge(m, src)
}
func (m *MsgWork) XXX_Size() int {
	return m.Size()
}
func (m *MsgWork) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWork.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWork proto.InternalMessageInfo

func (m *MsgWork) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWork) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *MsgWork) GetTaskid() string {
	if m != nil {
		return m.Taskid
	}
	return ""
}

func (m *MsgWork) GetBeginWork() uint64 {
	if m != nil {
		return m.BeginWork
	}
	return 0
}

func (m *MsgWork) GetFinishWork() uint64 {
	if m != nil {
		return m.FinishWork
	}
	return 0
}

func (m *MsgWork) GetWorkingTime() int32 {
	if m != nil {
		return m.WorkingTime
	}
	return 0
}

type MsgWorkResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgWorkResponse) Reset()         { *m = MsgWorkResponse{} }
func (m *MsgWorkResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWorkResponse) ProtoMessage()    {}
func (*MsgWorkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{3}
}
func (m *MsgWorkResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWorkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWorkResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWorkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWorkResponse.Merge(m, src)
}
func (m *MsgWorkResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWorkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWorkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWorkResponse proto.InternalMessageInfo

func (m *MsgWorkResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgBeginTask struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Taskid    string `protobuf:"bytes,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Assigner  string `protobuf:"bytes,3,opt,name=assigner,proto3" json:"assigner,omitempty"`
	BeginTask uint64 `protobuf:"varint,4,opt,name=beginTask,proto3" json:"beginTask,omitempty"`
	Deadline  uint64 `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Wager     string `protobuf:"bytes,6,opt,name=wager,proto3" json:"wager,omitempty"`
}

func (m *MsgBeginTask) Reset()         { *m = MsgBeginTask{} }
func (m *MsgBeginTask) String() string { return proto.CompactTextString(m) }
func (*MsgBeginTask) ProtoMessage()    {}
func (*MsgBeginTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{4}
}
func (m *MsgBeginTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBeginTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBeginTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBeginTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBeginTask.Merge(m, src)
}
func (m *MsgBeginTask) XXX_Size() int {
	return m.Size()
}
func (m *MsgBeginTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBeginTask.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBeginTask proto.InternalMessageInfo

func (m *MsgBeginTask) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBeginTask) GetTaskid() string {
	if m != nil {
		return m.Taskid
	}
	return ""
}

func (m *MsgBeginTask) GetAssigner() string {
	if m != nil {
		return m.Assigner
	}
	return ""
}

func (m *MsgBeginTask) GetBeginTask() uint64 {
	if m != nil {
		return m.BeginTask
	}
	return 0
}

func (m *MsgBeginTask) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *MsgBeginTask) GetWager() string {
	if m != nil {
		return m.Wager
	}
	return ""
}

type MsgBeginTaskResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgBeginTaskResponse) Reset()         { *m = MsgBeginTaskResponse{} }
func (m *MsgBeginTaskResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBeginTaskResponse) ProtoMessage()    {}
func (*MsgBeginTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{5}
}
func (m *MsgBeginTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBeginTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBeginTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBeginTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBeginTaskResponse.Merge(m, src)
}
func (m *MsgBeginTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBeginTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBeginTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBeginTaskResponse proto.InternalMessageInfo

func (m *MsgBeginTaskResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgFinishTask struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Taskid     uint64 `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	FinishTask uint64 `protobuf:"varint,3,opt,name=finishTask,proto3" json:"finishTask,omitempty"`
}

func (m *MsgFinishTask) Reset()         { *m = MsgFinishTask{} }
func (m *MsgFinishTask) String() string { return proto.CompactTextString(m) }
func (*MsgFinishTask) ProtoMessage()    {}
func (*MsgFinishTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{6}
}
func (m *MsgFinishTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinishTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinishTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinishTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinishTask.Merge(m, src)
}
func (m *MsgFinishTask) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinishTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinishTask.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinishTask proto.InternalMessageInfo

func (m *MsgFinishTask) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFinishTask) GetTaskid() uint64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *MsgFinishTask) GetFinishTask() uint64 {
	if m != nil {
		return m.FinishTask
	}
	return 0
}

type MsgFinishTaskResponse struct {
}

func (m *MsgFinishTaskResponse) Reset()         { *m = MsgFinishTaskResponse{} }
func (m *MsgFinishTaskResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinishTaskResponse) ProtoMessage()    {}
func (*MsgFinishTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d595ba97764ed13d, []int{7}
}
func (m *MsgFinishTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinishTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinishTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinishTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinishTaskResponse.Merge(m, src)
}
func (m *MsgFinishTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinishTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinishTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinishTaskResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "intravision.labour.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "intravision.labour.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgWork)(nil), "intravision.labour.MsgWork")
	proto.RegisterType((*MsgWorkResponse)(nil), "intravision.labour.MsgWorkResponse")
	proto.RegisterType((*MsgBeginTask)(nil), "intravision.labour.MsgBeginTask")
	proto.RegisterType((*MsgBeginTaskResponse)(nil), "intravision.labour.MsgBeginTaskResponse")
	proto.RegisterType((*MsgFinishTask)(nil), "intravision.labour.MsgFinishTask")
	proto.RegisterType((*MsgFinishTaskResponse)(nil), "intravision.labour.MsgFinishTaskResponse")
}

func init() { proto.RegisterFile("intravision/labour/tx.proto", fileDescriptor_d595ba97764ed13d) }

var fileDescriptor_d595ba97764ed13d = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0x34, 0x49, 0xeb, 0xd7, 0x02, 0xc2, 0x0a, 0xd4, 0x75, 0x91, 0x9b, 0xa6, 0x08,
	0x85, 0x22, 0x62, 0xb5, 0x48, 0x20, 0x55, 0x62, 0x20, 0x03, 0xea, 0x12, 0x09, 0x99, 0xa2, 0x4a,
	0x5d, 0xe0, 0x1c, 0x1f, 0xd7, 0x53, 0x6b, 0x5f, 0x74, 0xe7, 0xfe, 0xda, 0x10, 0x23, 0x13, 0x7f,
	0x06, 0x63, 0x07, 0x26, 0x36, 0xb6, 0x8e, 0x15, 0x13, 0x13, 0x42, 0xed, 0xd0, 0x89, 0xff, 0x01,
	0xdd, 0x9d, 0xed, 0x38, 0xa1, 0xa1, 0xb0, 0x24, 0x79, 0xef, 0xfb, 0xde, 0xbb, 0xef, 0xe7, 0xee,
	0x72, 0x30, 0x4f, 0xe3, 0x84, 0xa3, 0x7d, 0x2a, 0x28, 0x8b, 0xbd, 0x5d, 0x14, 0xb0, 0x3d, 0xee,
	0x25, 0x87, 0xed, 0x3e, 0x67, 0x09, 0xb3, 0xac, 0x82, 0xd8, 0xd6, 0xa2, 0x73, 0x13, 0x45, 0x34,
	0x66, 0x9e, 0xfa, 0xd4, 0x65, 0xce, 0x6c, 0x8f, 0x89, 0x88, 0x09, 0x2f, 0x12, 0xc4, 0xdb, 0x5f,
	0x91, 0x5f, 0xa9, 0x30, 0xa7, 0x85, 0xd7, 0x2a, 0xf2, 0x74, 0x90, 0x4a, 0x75, 0xc2, 0x08, 0xd3,
	0x79, 0xf9, 0x2b, 0xcd, 0x2e, 0x5c, 0xe2, 0xa6, 0x8f, 0x38, 0x8a, 0xb2, 0x36, 0x37, 0x5d, 0x2a,
	0x40, 0x02, 0x7b, 0xfb, 0x2b, 0x01, 0x4e, 0xd0, 0x8a, 0xd7, 0x63, 0x34, 0xd6, 0x7a, 0xf3, 0xab,
	0x01, 0x37, 0xba, 0x82, 0xbc, 0xea, 0x87, 0x28, 0xc1, 0x2f, 0x54, 0xa7, 0xf5, 0x18, 0x4c, 0xb4,
	0x97, 0x6c, 0x33, 0x4e, 0x93, 0x23, 0xdb, 0x68, 0x18, 0x2d, 0xb3, 0x63, 0x7f, 0xfb, 0xfc, 0xb0,
	0x9e, 0xfa, 0x79, 0x16, 0x86, 0x1c, 0x0b, 0xf1, 0x32, 0xe1, 0x34, 0x26, 0xfe, 0xa0, 0xd4, 0x7a,
	0x0a, 0x35, 0xbd, 0xb6, 0x5d, 0x6e, 0x18, 0xad, 0xe9, 0x55, 0xa7, 0xfd, 0xe7, 0x76, 0xb4, 0xf5,
	0x1a, 0x1d, 0xf3, 0xe4, 0xc7, 0x42, 0xe9, 0xd3, 0xc5, 0xf1, 0xb2, 0xe1, 0xa7, 0x4d, 0x6b, 0x4f,
	0xde, 0x5f, 0x1c, 0x2f, 0x0f, 0xc6, 0x7d, 0xb8, 0x38, 0x5e, 0xbe, 0x5b, 0xc4, 0x3b, 0xcc, 0x00,
	0x47, 0xfc, 0x36, 0xe7, 0x60, 0x76, 0x24, 0xe5, 0x63, 0xd1, 0x67, 0xb1, 0xc0, 0x12, 0x6f, 0xb2,
	0x2b, 0xc8, 0x26, 0xe3, 0x3b, 0x96, 0x0d, 0x93, 0x3d, 0x8e, 0x51, 0xc2, 0xb8, 0x86, 0xf2, 0xb3,
	0xd0, 0xba, 0x0d, 0xb5, 0x03, 0xc6, 0x77, 0x30, 0x57, 0xc6, 0x4d, 0x3f, 0x8d, 0x64, 0x3e, 0x41,
	0x62, 0x87, 0x86, 0xf6, 0x84, 0xce, 0xeb, 0xc8, 0xba, 0x03, 0x66, 0x80, 0x09, 0x8d, 0xe5, 0x58,
	0xbb, 0xd2, 0x30, 0x5a, 0x15, 0x7f, 0x90, 0xb0, 0x5c, 0x80, 0xb7, 0x34, 0xa6, 0x62, 0x5b, 0xc9,
	0x55, 0x25, 0x17, 0x32, 0x56, 0x03, 0xa6, 0xe5, 0x7c, 0x1a, 0x93, 0x0d, 0x1a, 0x61, 0xbb, 0xd6,
	0x30, 0x5a, 0x55, 0xbf, 0x98, 0x5a, 0x9b, 0x91, 0x3b, 0x91, 0xb9, 0x6b, 0x2e, 0xaa, 0x13, 0x92,
	0xad, 0x19, 0x96, 0x75, 0x1d, 0xca, 0x34, 0x54, 0x14, 0x15, 0xbf, 0x4c, 0xc3, 0xe6, 0x17, 0x03,
	0x66, 0xba, 0x82, 0x74, 0xa4, 0x87, 0x0d, 0x24, 0xae, 0x60, 0x4d, 0x99, 0xca, 0x43, 0x4c, 0x0e,
	0x4c, 0x21, 0x21, 0x28, 0x89, 0x31, 0x4f, 0x69, 0xf3, 0x38, 0xe7, 0x95, 0xa3, 0x87, 0x78, 0xd5,
	0x5a, 0x0e, 0x4c, 0x85, 0x18, 0x85, 0xbb, 0x34, 0xc6, 0x29, 0x6d, 0x1e, 0x5b, 0x75, 0xa8, 0x1e,
	0x20, 0x82, 0xb9, 0xa2, 0x34, 0x7d, 0x1d, 0x8c, 0xf0, 0xdd, 0x83, 0x7a, 0xd1, 0xfb, 0x58, 0x48,
	0x06, 0xd7, 0xba, 0x82, 0x3c, 0x57, 0x1b, 0xf9, 0x5f, 0x90, 0x95, 0x1c, 0x32, 0x3f, 0x1a, 0x45,
	0x32, 0x51, 0x3c, 0x1a, 0x99, 0x19, 0x31, 0x36, 0x0b, 0xb7, 0x86, 0x16, 0xcc, 0x9c, 0xad, 0xfe,
	0x2a, 0xc3, 0x44, 0x57, 0x10, 0xeb, 0x0d, 0xcc, 0x0c, 0xfd, 0x71, 0x96, 0x2e, 0xbb, 0xf0, 0x23,
	0x57, 0xd3, 0x79, 0xf0, 0x0f, 0x45, 0xf9, 0x1e, 0xac, 0x43, 0x45, 0xdd, 0x99, 0xf9, 0x31, 0x4d,
	0x52, 0x74, 0x96, 0xfe, 0x22, 0xe6, 0x93, 0x36, 0xc1, 0x1c, 0x5c, 0x8f, 0xc6, 0x98, 0x8e, 0xbc,
	0xc2, 0x69, 0x5d, 0x55, 0x91, 0x0f, 0xde, 0x02, 0x28, 0x9c, 0xc9, 0xe2, 0x98, 0xbe, 0x41, 0x89,
	0x73, 0xff, 0xca, 0x92, 0x6c, 0xb6, 0x53, 0x7d, 0x27, 0x5f, 0x88, 0xce, 0xfa, 0xc9, 0x99, 0x6b,
	0x9c, 0x9e, 0xb9, 0xc6, 0xcf, 0x33, 0xd7, 0xf8, 0x78, 0xee, 0x96, 0x4e, 0xcf, 0xdd, 0xd2, 0xf7,
	0x73, 0xb7, 0xb4, 0xd5, 0x26, 0x34, 0xd9, 0xde, 0x0b, 0xda, 0x3d, 0x16, 0x79, 0x11, 0xe6, 0xbb,
	0x34, 0x26, 0xcc, 0xbb, 0xf4, 0xd1, 0x48, 0x8e, 0xfa, 0x58, 0x04, 0x35, 0xf5, 0xea, 0x3d, 0xfa,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x99, 0x36, 0x21, 0xc6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	Work(ctx context.Context, in *MsgWork, opts ...grpc.CallOption) (*MsgWorkResponse, error)
	BeginTask(ctx context.Context, in *MsgBeginTask, opts ...grpc.CallOption) (*MsgBeginTaskResponse, error)
	FinishTask(ctx context.Context, in *MsgFinishTask, opts ...grpc.CallOption) (*MsgFinishTaskResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/intravision.labour.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Work(ctx context.Context, in *MsgWork, opts ...grpc.CallOption) (*MsgWorkResponse, error) {
	out := new(MsgWorkResponse)
	err := c.cc.Invoke(ctx, "/intravision.labour.Msg/Work", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BeginTask(ctx context.Context, in *MsgBeginTask, opts ...grpc.CallOption) (*MsgBeginTaskResponse, error) {
	out := new(MsgBeginTaskResponse)
	err := c.cc.Invoke(ctx, "/intravision.labour.Msg/BeginTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinishTask(ctx context.Context, in *MsgFinishTask, opts ...grpc.CallOption) (*MsgFinishTaskResponse, error) {
	out := new(MsgFinishTaskResponse)
	err := c.cc.Invoke(ctx, "/intravision.labour.Msg/FinishTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	Work(context.Context, *MsgWork) (*MsgWorkResponse, error)
	BeginTask(context.Context, *MsgBeginTask) (*MsgBeginTaskResponse, error)
	FinishTask(context.Context, *MsgFinishTask) (*MsgFinishTaskResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) Work(ctx context.Context, req *MsgWork) (*MsgWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Work not implemented")
}
func (*UnimplementedMsgServer) BeginTask(ctx context.Context, req *MsgBeginTask) (*MsgBeginTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTask not implemented")
}
func (*UnimplementedMsgServer) FinishTask(ctx context.Context, req *MsgFinishTask) (*MsgFinishTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishTask not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.labour.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Work_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWork)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Work(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.labour.Msg/Work",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Work(ctx, req.(*MsgWork))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BeginTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBeginTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BeginTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.labour.Msg/BeginTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BeginTask(ctx, req.(*MsgBeginTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinishTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.labour.Msg/FinishTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinishTask(ctx, req.(*MsgFinishTask))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intravision.labour.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "Work",
			Handler:    _Msg_Work_Handler,
		},
		{
			MethodName: "BeginTask",
			Handler:    _Msg_BeginTask_Handler,
		},
		{
			MethodName: "FinishTask",
			Handler:    _Msg_FinishTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intravision/labour/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWork) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WorkingTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WorkingTime))
		i--
		dAtA[i] = 0x30
	}
	if m.FinishWork != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FinishWork))
		i--
		dAtA[i] = 0x28
	}
	if m.BeginWork != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeginWork))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Taskid) > 0 {
		i -= len(m.Taskid)
		copy(dAtA[i:], m.Taskid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Taskid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWorkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWorkResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWorkResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBeginTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBeginTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBeginTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Wager) > 0 {
		i -= len(m.Wager)
		copy(dAtA[i:], m.Wager)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Wager)))
		i--
		dAtA[i] = 0x32
	}
	if m.Deadline != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x28
	}
	if m.BeginTask != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeginTask))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Assigner) > 0 {
		i -= len(m.Assigner)
		copy(dAtA[i:], m.Assigner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Assigner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Taskid) > 0 {
		i -= len(m.Taskid)
		copy(dAtA[i:], m.Taskid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Taskid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBeginTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBeginTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBeginTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinishTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinishTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinishTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinishTask != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FinishTask))
		i--
		dAtA[i] = 0x18
	}
	if m.Taskid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Taskid))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinishTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinishTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinishTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Taskid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BeginWork != 0 {
		n += 1 + sovTx(uint64(m.BeginWork))
	}
	if m.FinishWork != 0 {
		n += 1 + sovTx(uint64(m.FinishWork))
	}
	if m.WorkingTime != 0 {
		n += 1 + sovTx(uint64(m.WorkingTime))
	}
	return n
}

func (m *MsgWorkResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgBeginTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Taskid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Assigner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BeginTask != 0 {
		n += 1 + sovTx(uint64(m.BeginTask))
	}
	if m.Deadline != 0 {
		n += 1 + sovTx(uint64(m.Deadline))
	}
	l = len(m.Wager)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBeginTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgFinishTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Taskid != 0 {
		n += 1 + sovTx(uint64(m.Taskid))
	}
	if m.FinishTask != 0 {
		n += 1 + sovTx(uint64(m.FinishTask))
	}
	return n
}

func (m *MsgFinishTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWork) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taskid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taskid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeginWork", wireType)
			}
			m.BeginWork = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeginWork |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinishWork", wireType)
			}
			m.FinishWork = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinishWork |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkingTime", wireType)
			}
			m.WorkingTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkingTime |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWorkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWorkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWorkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBeginTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBeginTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBeginTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taskid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taskid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assigner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assigner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeginTask", wireType)
			}
			m.BeginTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeginTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBeginTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBeginTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBeginTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinishTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinishTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinishTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taskid", wireType)
			}
			m.Taskid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Taskid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinishTask", wireType)
			}
			m.FinishTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinishTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinishTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinishTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinishTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
