// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intravision/gainsharing/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the gainsharing module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params           Params        `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	MechanismList    []Mechanism   `protobuf:"bytes,2,rep,name=mechanismList,proto3" json:"mechanismList"`
	MechanismCount   uint64        `protobuf:"varint,3,opt,name=mechanismCount,proto3" json:"mechanismCount,omitempty"`
	PerformanceList  []Performance `protobuf:"bytes,4,rep,name=performanceList,proto3" json:"performanceList"`
	PerformanceCount uint64        `protobuf:"varint,5,opt,name=performanceCount,proto3" json:"performanceCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eacb0a530fdc67f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMechanismList() []Mechanism {
	if m != nil {
		return m.MechanismList
	}
	return nil
}

func (m *GenesisState) GetMechanismCount() uint64 {
	if m != nil {
		return m.MechanismCount
	}
	return 0
}

func (m *GenesisState) GetPerformanceList() []Performance {
	if m != nil {
		return m.PerformanceList
	}
	return nil
}

func (m *GenesisState) GetPerformanceCount() uint64 {
	if m != nil {
		return m.PerformanceCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "intravision.gainsharing.GenesisState")
}

func init() {
	proto.RegisterFile("intravision/gainsharing/genesis.proto", fileDescriptor_4eacb0a530fdc67f)
}

var fileDescriptor_4eacb0a530fdc67f = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0x86, 0xa7, 0xc0, 0x47, 0xf2, 0x15, 0x7f, 0x27, 0x26, 0x12, 0x16, 0x85, 0x10, 0x54, 0x64,
	0x31, 0x4d, 0xe0, 0x0e, 0xc6, 0x85, 0x1b, 0x31, 0x06, 0x5d, 0xb9, 0x2b, 0xa4, 0x96, 0x26, 0xb6,
	0x25, 0x6d, 0x31, 0x7a, 0x17, 0x5e, 0x86, 0x4b, 0x2f, 0x83, 0x85, 0x0b, 0x96, 0xae, 0x8c, 0x61,
	0x16, 0xde, 0x86, 0xa1, 0x33, 0xe2, 0x80, 0xe9, 0x66, 0xd2, 0xbc, 0x79, 0xce, 0x79, 0xe6, 0xcd,
	0x81, 0x47, 0x5c, 0x5a, 0x4d, 0x1e, 0xb8, 0xe1, 0x4a, 0x62, 0x46, 0xb8, 0x34, 0x63, 0xa2, 0xb9,
	0x64, 0x98, 0x51, 0x49, 0x0d, 0x37, 0xd1, 0x44, 0x2b, 0xab, 0xc2, 0xc3, 0x1c, 0x16, 0xe5, 0xb0,
	0xda, 0x3e, 0x11, 0x5c, 0x2a, 0xec, 0xbe, 0x29, 0x5b, 0x3b, 0x60, 0x8a, 0x29, 0xf7, 0xc4, 0xcb,
	0x57, 0x96, 0xb6, 0x7c, 0xa2, 0x09, 0xd1, 0x44, 0x64, 0x9e, 0xda, 0x89, 0x8f, 0x12, 0x74, 0x34,
	0x26, 0x92, 0x1b, 0x91, 0x81, 0xa7, 0xde, 0x75, 0x54, 0xdf, 0x29, 0x2d, 0x88, 0x1c, 0xd1, 0x14,
	0x6d, 0xbe, 0x15, 0xe0, 0xd6, 0x79, 0xda, 0xe6, 0xda, 0x12, 0x4b, 0xc3, 0x18, 0x96, 0x53, 0x69,
	0x15, 0x34, 0x40, 0xbb, 0xd2, 0xad, 0x47, 0x9e, 0x76, 0xd1, 0x95, 0xc3, 0xe2, 0xff, 0xb3, 0x8f,
	0x7a, 0xf0, 0xf2, 0xf5, 0xda, 0x01, 0x83, 0x6c, 0x32, 0xbc, 0x84, 0xdb, 0xab, 0x5f, 0xba, 0xe0,
	0xc6, 0x56, 0x0b, 0x8d, 0x62, 0xbb, 0xd2, 0x6d, 0x7a, 0x57, 0xf5, 0x7f, 0xe8, 0xb8, 0xb4, 0xdc,
	0x36, 0x58, 0x1f, 0x0f, 0x8f, 0xe1, 0xce, 0x2a, 0x38, 0x53, 0x53, 0x69, 0xab, 0xc5, 0x06, 0x68,
	0x97, 0x06, 0x1b, 0x69, 0x78, 0x03, 0x77, 0x73, 0x0d, 0x9d, 0xb9, 0xe4, 0xcc, 0x2d, 0x7f, 0x89,
	0x5f, 0x3e, 0x73, 0x6f, 0xae, 0x08, 0x3b, 0x70, 0x2f, 0x17, 0xa5, 0xfe, 0x7f, 0xce, 0xff, 0x27,
	0x8f, 0xfb, 0xb3, 0x05, 0x02, 0xf3, 0x05, 0x02, 0x9f, 0x0b, 0x04, 0x9e, 0x13, 0x14, 0xcc, 0x13,
	0x14, 0xbc, 0x27, 0x28, 0xb8, 0xed, 0x31, 0x6e, 0xc7, 0xd3, 0x61, 0x34, 0x52, 0x02, 0x0b, 0xaa,
	0xef, 0xb9, 0x64, 0x0a, 0xe7, 0xef, 0xf4, 0xb8, 0x76, 0x29, 0xfb, 0x34, 0xa1, 0x66, 0x58, 0x76,
	0x47, 0xea, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xab, 0xe6, 0xd4, 0x85, 0x89, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PerformanceCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PerformanceCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PerformanceList) > 0 {
		for iNdEx := len(m.PerformanceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerformanceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.MechanismCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MechanismCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MechanismList) > 0 {
		for iNdEx := len(m.MechanismList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MechanismList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MechanismList) > 0 {
		for _, e := range m.MechanismList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.MechanismCount != 0 {
		n += 1 + sovGenesis(uint64(m.MechanismCount))
	}
	if len(m.PerformanceList) > 0 {
		for _, e := range m.PerformanceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PerformanceCount != 0 {
		n += 1 + sovGenesis(uint64(m.PerformanceCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MechanismList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MechanismList = append(m.MechanismList, Mechanism{})
			if err := m.MechanismList[len(m.MechanismList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MechanismCount", wireType)
			}
			m.MechanismCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MechanismCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerformanceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerformanceList = append(m.PerformanceList, Performance{})
			if err := m.PerformanceList[len(m.PerformanceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerformanceCount", wireType)
			}
			m.PerformanceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PerformanceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
