// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intravision/gainsharing/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgSetMechanism struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Metrics       string `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Coefficients  string `protobuf:"bytes,3,opt,name=coefficients,proto3" json:"coefficients,omitempty"`
	ConvergeLimit string `protobuf:"bytes,4,opt,name=convergeLimit,proto3" json:"convergeLimit,omitempty"`
	Slope         string `protobuf:"bytes,5,opt,name=slope,proto3" json:"slope,omitempty"`
}

func (m *MsgSetMechanism) Reset()         { *m = MsgSetMechanism{} }
func (m *MsgSetMechanism) String() string { return proto.CompactTextString(m) }
func (*MsgSetMechanism) ProtoMessage()    {}
func (*MsgSetMechanism) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{2}
}
func (m *MsgSetMechanism) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMechanism) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMechanism.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMechanism) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMechanism.Merge(m, src)
}
func (m *MsgSetMechanism) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMechanism) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMechanism.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMechanism proto.InternalMessageInfo

func (m *MsgSetMechanism) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetMechanism) GetMetrics() string {
	if m != nil {
		return m.Metrics
	}
	return ""
}

func (m *MsgSetMechanism) GetCoefficients() string {
	if m != nil {
		return m.Coefficients
	}
	return ""
}

func (m *MsgSetMechanism) GetConvergeLimit() string {
	if m != nil {
		return m.ConvergeLimit
	}
	return ""
}

func (m *MsgSetMechanism) GetSlope() string {
	if m != nil {
		return m.Slope
	}
	return ""
}

type MsgSetMechanismResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgSetMechanismResponse) Reset()         { *m = MsgSetMechanismResponse{} }
func (m *MsgSetMechanismResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetMechanismResponse) ProtoMessage()    {}
func (*MsgSetMechanismResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{3}
}
func (m *MsgSetMechanismResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMechanismResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMechanismResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMechanismResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMechanismResponse.Merge(m, src)
}
func (m *MsgSetMechanismResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMechanismResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMechanismResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMechanismResponse proto.InternalMessageInfo

func (m *MsgSetMechanismResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCalculatePerformance struct {
	Creator string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Mid     int32      `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Wager   types.Coin `protobuf:"bytes,3,opt,name=wager,proto3" json:"wager"`
	Earner  string     `protobuf:"bytes,4,opt,name=earner,proto3" json:"earner,omitempty"`
	Taskid  string     `protobuf:"bytes,5,opt,name=taskid,proto3" json:"taskid,omitempty"`
}

func (m *MsgCalculatePerformance) Reset()         { *m = MsgCalculatePerformance{} }
func (m *MsgCalculatePerformance) String() string { return proto.CompactTextString(m) }
func (*MsgCalculatePerformance) ProtoMessage()    {}
func (*MsgCalculatePerformance) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{4}
}
func (m *MsgCalculatePerformance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCalculatePerformance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCalculatePerformance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCalculatePerformance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCalculatePerformance.Merge(m, src)
}
func (m *MsgCalculatePerformance) XXX_Size() int {
	return m.Size()
}
func (m *MsgCalculatePerformance) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCalculatePerformance.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCalculatePerformance proto.InternalMessageInfo

func (m *MsgCalculatePerformance) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCalculatePerformance) GetMid() int32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *MsgCalculatePerformance) GetWager() types.Coin {
	if m != nil {
		return m.Wager
	}
	return types.Coin{}
}

func (m *MsgCalculatePerformance) GetEarner() string {
	if m != nil {
		return m.Earner
	}
	return ""
}

func (m *MsgCalculatePerformance) GetTaskid() string {
	if m != nil {
		return m.Taskid
	}
	return ""
}

type MsgCalculatePerformanceResponse struct {
	Id     int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reward types.Coin `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward"`
}

func (m *MsgCalculatePerformanceResponse) Reset()         { *m = MsgCalculatePerformanceResponse{} }
func (m *MsgCalculatePerformanceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCalculatePerformanceResponse) ProtoMessage()    {}
func (*MsgCalculatePerformanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d620c57a55764c5, []int{5}
}
func (m *MsgCalculatePerformanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCalculatePerformanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCalculatePerformanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCalculatePerformanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCalculatePerformanceResponse.Merge(m, src)
}
func (m *MsgCalculatePerformanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCalculatePerformanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCalculatePerformanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCalculatePerformanceResponse proto.InternalMessageInfo

func (m *MsgCalculatePerformanceResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgCalculatePerformanceResponse) GetReward() types.Coin {
	if m != nil {
		return m.Reward
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "intravision.gainsharing.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "intravision.gainsharing.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSetMechanism)(nil), "intravision.gainsharing.MsgSetMechanism")
	proto.RegisterType((*MsgSetMechanismResponse)(nil), "intravision.gainsharing.MsgSetMechanismResponse")
	proto.RegisterType((*MsgCalculatePerformance)(nil), "intravision.gainsharing.MsgCalculatePerformance")
	proto.RegisterType((*MsgCalculatePerformanceResponse)(nil), "intravision.gainsharing.MsgCalculatePerformanceResponse")
}

func init() { proto.RegisterFile("intravision/gainsharing/tx.proto", fileDescriptor_2d620c57a55764c5) }

var fileDescriptor_2d620c57a55764c5 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xbd, 0x6e, 0xdb, 0x3c,
	0x14, 0xb5, 0x9c, 0xc8, 0x1f, 0xcc, 0xf8, 0xeb, 0x0f, 0x61, 0x34, 0x8a, 0x07, 0x25, 0x10, 0x32,
	0x24, 0x01, 0x2a, 0x35, 0x09, 0xfa, 0x83, 0xa0, 0x4b, 0x9d, 0xb5, 0x06, 0x0a, 0x05, 0x5d, 0xba,
	0x14, 0xb4, 0xc4, 0xc8, 0x4c, 0x2d, 0x52, 0x20, 0x19, 0x27, 0xd9, 0x8a, 0x8c, 0x9d, 0xfa, 0x18,
	0x1d, 0x03, 0xb4, 0x53, 0x9f, 0x20, 0x40, 0x97, 0xa0, 0x53, 0xa7, 0xa2, 0x88, 0x07, 0xa3, 0x6f,
	0x51, 0x88, 0xa4, 0x1a, 0xdb, 0xb0, 0xdc, 0x76, 0xb1, 0x79, 0xef, 0x3d, 0x97, 0xf7, 0x1c, 0xf2,
	0x50, 0x60, 0x8d, 0x50, 0xc9, 0xd1, 0x80, 0x08, 0xc2, 0x68, 0x90, 0x20, 0x42, 0x45, 0x0f, 0x71,
	0x42, 0x93, 0x40, 0x9e, 0xfa, 0x19, 0x67, 0x92, 0xc1, 0xe5, 0x31, 0x84, 0x3f, 0x86, 0x68, 0xdd,
	0x45, 0x29, 0xa1, 0x2c, 0x50, 0xbf, 0x1a, 0xdb, 0x5a, 0x8e, 0x98, 0x48, 0x99, 0x08, 0x52, 0x91,
	0x04, 0x83, 0xed, 0xfc, 0xcf, 0x14, 0x56, 0x74, 0xe1, 0xb5, 0x8a, 0x02, 0x1d, 0x98, 0x52, 0x33,
	0x61, 0x09, 0xd3, 0xf9, 0x7c, 0x65, 0xb2, 0xeb, 0x65, 0xbc, 0x32, 0xc4, 0x51, 0x5a, 0xf4, 0xba,
	0x66, 0x5e, 0x17, 0x09, 0x1c, 0x0c, 0xb6, 0xbb, 0x58, 0xa2, 0xed, 0x20, 0x62, 0x84, 0xea, 0xba,
	0xf7, 0xc5, 0x02, 0xb7, 0x3b, 0x22, 0x79, 0x99, 0xc5, 0x48, 0xe2, 0x17, 0xaa, 0x13, 0x3e, 0x02,
	0x75, 0x74, 0x2c, 0x7b, 0x8c, 0x13, 0x79, 0xe6, 0x58, 0x6b, 0xd6, 0x46, 0xbd, 0xed, 0x7c, 0xfd,
	0x74, 0xbf, 0x69, 0x48, 0x3d, 0x8b, 0x63, 0x8e, 0x85, 0x38, 0x90, 0xf9, 0xb4, 0xf0, 0x06, 0x0a,
	0xdb, 0xa0, 0xa6, 0x67, 0x3b, 0xd5, 0x35, 0x6b, 0x63, 0x69, 0x67, 0xd5, 0x2f, 0x39, 0x18, 0x5f,
	0x0f, 0x6a, 0xd7, 0x2f, 0xbf, 0xaf, 0x56, 0x3e, 0x8c, 0x2e, 0xb6, 0xac, 0xd0, 0x74, 0xee, 0x3d,
	0x3d, 0x1f, 0x5d, 0x6c, 0xdd, 0xec, 0xf9, 0x6e, 0x74, 0xb1, 0xb5, 0x39, 0x2e, 0xf4, 0x74, 0x42,
	0xea, 0x14, 0x73, 0x6f, 0x05, 0x2c, 0x4f, 0xa5, 0x42, 0x2c, 0x32, 0x46, 0x05, 0xf6, 0x3e, 0x6a,
	0xa1, 0x07, 0x58, 0x76, 0x70, 0xd4, 0x43, 0x94, 0x88, 0x14, 0x3a, 0xe0, 0xbf, 0x88, 0x63, 0x24,
	0x19, 0xd7, 0x32, 0xc3, 0x22, 0xcc, 0x2b, 0x29, 0x96, 0x9c, 0x44, 0x5a, 0x4b, 0x3d, 0x2c, 0x42,
	0xe8, 0x81, 0x46, 0xc4, 0xf0, 0xe1, 0x21, 0x89, 0x08, 0xa6, 0x52, 0x38, 0x0b, 0xaa, 0x3c, 0x91,
	0x83, 0xeb, 0xe0, 0xff, 0x88, 0xd1, 0x01, 0xe6, 0x09, 0x7e, 0x4e, 0x52, 0x22, 0x9d, 0x45, 0x05,
	0x9a, 0x4c, 0xc2, 0x26, 0xb0, 0x45, 0x9f, 0x65, 0xd8, 0xb1, 0x55, 0x55, 0x07, 0x7b, 0x8d, 0xfc,
	0x00, 0x0a, 0x1e, 0xde, 0xa6, 0x12, 0x34, 0x4e, 0xba, 0x10, 0x04, 0x6f, 0x81, 0x2a, 0x89, 0x15,
	0x6f, 0x3b, 0xac, 0x92, 0xd8, 0xfb, 0x6c, 0x29, 0xec, 0x3e, 0xea, 0x47, 0xc7, 0xfd, 0x5c, 0x3f,
	0xe6, 0x87, 0x8c, 0xa7, 0x88, 0x46, 0x78, 0x8e, 0xd0, 0x3b, 0x60, 0x21, 0x25, 0xb1, 0x12, 0x69,
	0x87, 0xf9, 0x12, 0x3e, 0x04, 0xf6, 0x09, 0x4a, 0x30, 0x57, 0xca, 0x96, 0x76, 0x56, 0x7c, 0x73,
	0xed, 0xb9, 0x83, 0x7c, 0xe3, 0x20, 0x7f, 0x9f, 0x11, 0xda, 0x5e, 0xcc, 0xaf, 0x2f, 0xd4, 0x68,
	0x78, 0x0f, 0xd4, 0x30, 0xe2, 0x14, 0x73, 0x23, 0xd6, 0x44, 0x79, 0x5e, 0x22, 0xf1, 0x86, 0xc4,
	0x46, 0xa6, 0x89, 0xa6, 0x74, 0x1e, 0x81, 0xd5, 0x12, 0xee, 0x65, 0x7a, 0xe1, 0x63, 0x50, 0xe3,
	0xf8, 0x04, 0xf1, 0xd8, 0xb8, 0xed, 0x8f, 0x44, 0x0d, 0x7c, 0xe7, 0x67, 0x15, 0x2c, 0x74, 0x44,
	0x02, 0x8f, 0x40, 0x63, 0xc2, 0xf6, 0x1b, 0xa5, 0x76, 0x9d, 0xf2, 0x54, 0xeb, 0xc1, 0xdf, 0x22,
	0x7f, 0x93, 0x3f, 0x02, 0x8d, 0x09, 0xe7, 0xcd, 0x9d, 0x35, 0x8e, 0x9c, 0x3f, 0x6b, 0xa6, 0x31,
	0xce, 0x2d, 0xd0, 0x9c, 0xe9, 0x82, 0xb9, 0x5b, 0xcd, 0xea, 0x68, 0x3d, 0xf9, 0xd7, 0x8e, 0x82,
	0x44, 0xcb, 0x7e, 0x9b, 0x3f, 0xeb, 0x76, 0xe7, 0xf2, 0xda, 0xb5, 0xae, 0xae, 0x5d, 0xeb, 0xc7,
	0xb5, 0x6b, 0xbd, 0x1f, 0xba, 0x95, 0xab, 0xa1, 0x5b, 0xf9, 0x36, 0x74, 0x2b, 0xaf, 0x76, 0x13,
	0x22, 0x7b, 0xc7, 0x5d, 0x3f, 0x62, 0x69, 0x90, 0x62, 0xde, 0x27, 0x34, 0x61, 0x41, 0xf9, 0x4b,
	0x97, 0x67, 0x19, 0x16, 0xdd, 0x9a, 0xfa, 0x68, 0xed, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x8a, 0xcf, 0xc4, 0x94, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SetMechanism(ctx context.Context, in *MsgSetMechanism, opts ...grpc.CallOption) (*MsgSetMechanismResponse, error)
	CalculatePerformance(ctx context.Context, in *MsgCalculatePerformance, opts ...grpc.CallOption) (*MsgCalculatePerformanceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/intravision.gainsharing.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetMechanism(ctx context.Context, in *MsgSetMechanism, opts ...grpc.CallOption) (*MsgSetMechanismResponse, error) {
	out := new(MsgSetMechanismResponse)
	err := c.cc.Invoke(ctx, "/intravision.gainsharing.Msg/SetMechanism", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CalculatePerformance(ctx context.Context, in *MsgCalculatePerformance, opts ...grpc.CallOption) (*MsgCalculatePerformanceResponse, error) {
	out := new(MsgCalculatePerformanceResponse)
	err := c.cc.Invoke(ctx, "/intravision.gainsharing.Msg/CalculatePerformance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SetMechanism(context.Context, *MsgSetMechanism) (*MsgSetMechanismResponse, error)
	CalculatePerformance(context.Context, *MsgCalculatePerformance) (*MsgCalculatePerformanceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SetMechanism(ctx context.Context, req *MsgSetMechanism) (*MsgSetMechanismResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMechanism not implemented")
}
func (*UnimplementedMsgServer) CalculatePerformance(ctx context.Context, req *MsgCalculatePerformance) (*MsgCalculatePerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePerformance not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.gainsharing.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetMechanism_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetMechanism)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetMechanism(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.gainsharing.Msg/SetMechanism",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetMechanism(ctx, req.(*MsgSetMechanism))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CalculatePerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCalculatePerformance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CalculatePerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intravision.gainsharing.Msg/CalculatePerformance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CalculatePerformance(ctx, req.(*MsgCalculatePerformance))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intravision.gainsharing.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SetMechanism",
			Handler:    _Msg_SetMechanism_Handler,
		},
		{
			MethodName: "CalculatePerformance",
			Handler:    _Msg_CalculatePerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intravision/gainsharing/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetMechanism) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMechanism) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMechanism) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Slope) > 0 {
		i -= len(m.Slope)
		copy(dAtA[i:], m.Slope)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Slope)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ConvergeLimit) > 0 {
		i -= len(m.ConvergeLimit)
		copy(dAtA[i:], m.ConvergeLimit)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConvergeLimit)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Coefficients) > 0 {
		i -= len(m.Coefficients)
		copy(dAtA[i:], m.Coefficients)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Coefficients)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Metrics) > 0 {
		i -= len(m.Metrics)
		copy(dAtA[i:], m.Metrics)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metrics)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetMechanismResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMechanismResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMechanismResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCalculatePerformance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCalculatePerformance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCalculatePerformance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Taskid) > 0 {
		i -= len(m.Taskid)
		copy(dAtA[i:], m.Taskid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Taskid)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Earner) > 0 {
		i -= len(m.Earner)
		copy(dAtA[i:], m.Earner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Earner)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Wager.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Mid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Mid))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCalculatePerformanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCalculatePerformanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCalculatePerformanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetMechanism) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Metrics)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Coefficients)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConvergeLimit)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Slope)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetMechanismResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCalculatePerformance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Mid != 0 {
		n += 1 + sovTx(uint64(m.Mid))
	}
	l = m.Wager.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Earner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Taskid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCalculatePerformanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = m.Reward.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMechanism) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMechanism: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMechanism: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coefficients", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coefficients = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergeLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConvergeLimit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMechanismResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMechanismResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMechanismResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCalculatePerformance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCalculatePerformance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCalculatePerformance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mid", wireType)
			}
			m.Mid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wager", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Wager.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Earner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Earner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taskid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taskid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCalculatePerformanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCalculatePerformanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCalculatePerformanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
